# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemoryGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for MemoryGame
  pod 'AFNetworking'
  pod 'FSImageViewer_image_resize'
  pod 'SVProgressHUD'
  target 'MemoryGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemoryGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
