# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "406a64d0-8bfa-4ead-afe0-e233b0e523e3"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # cocoapods

  # build your iOS app
	cert
	sigh
  gym(

	scheme: "MemoryGame",
    export_method: "development"
  )

  # upload to HockeyApp
  hockey(
	# api_token: "7f6cfd64f84b41caa2db366bc782e1a3"
  )
end
